### ISSUE TITLE
Vars file currently hardcoded, change to var

### ISSUE THREAD

**Issue by davidtluong** [opendatapolicing/opendatapolicing#161]
Replace the hardcoded version:
```
/usr/local/src/opendatapolicing-ansible/vaults/{{ VAULT_ID }}/vault
```
With something like the following in all files:
```
{{ PROJECTS_DIR }}/opendatapolicing-ansible/vaults/{{ VAULT_ID }}/vault
```

Can be done after hackathon is done with a global sed replace.  Also, remember to add a default value for PROJECTS_DIR var to the defaults.yml for all roles utilizing hardcoded vars_files.

**Comment by cwilkers** [comment]
I can add this, I was just working on those lines.
