### ISSUE TITLE
Setup OpenShift cluster

### ISSUE THREAD

**Issue by computate** [opendatapolicing/opendatapolicing#2]
Red Hat employees can obtain a free OpenShift cluster with 4GiB RAM and 10 GiB storage with their people manager approval here: 

https://employee.openshift.com/register/employee/introduction

You may also obtain an OpenShift cluster by registering for the "OpenShift 4.4 Shared Environment" from the catalog at https://rhpds.redhat.com

**Comment by carbonin** [comment]
Have a cluster up at https://console-openshift-console.apps.shared-na4.na4.openshift.opentlc.com
It's valid for a week and allows public access to the application we deploy.
If someone else has access to these environments set up already, can you test if you can also access the environment?
@rh-dluong ?

**Comment by davidtluong** [comment]
I think I got the openshift online working, will need everyone's rh id's though according to https://github.com/opendatapolicing/opendatapolicing/issues/3

**Comment by haircommander** [comment]
should we create a document for people to add their rh IDs to so they can be added to the project?

**Comment by davidtluong** [comment]
The Web Console URL for this cluster is http://console-openshift-console.apps.shared-na4.na4.openshift.opentlc.com 
The API URl for this cluster is https://api.shared-rhpds4.rhpds4.openshift.opentlc.com:6443

You can use your OpenTLC/RHPDS User ID and Password to log into the cluster.

**Comment by davidtluong** [comment]
@haircommander We're making a thread in the chat so you can input your openTLC/RHPDS user id so Nick can add you to the project.  You can also log in right now, you just won't have any projects.
