### ISSUE TITLE
Create an OpenShift project

### ISSUE THREAD

**Issue by computate** [opendatapolicing/opendatapolicing#3]
As a team, create an OpenShift project and share the project with the team. 

* Login to your OpenShift environment here: https://console.rh-us-east-1.openshift.com
* Create a new OpenShift project named: opendatapolicing

### Share the OpenShift project with the other users

* You can find your Red Hat Login ID by logging into this site here: https://sso.redhat.com/auth/realms/redhat-external/account/
* You can add your Red Hat Login ID to your list of login IDs (REDHAT_OPENSHIFT_LOGIN_IDS) to the project here if you want to regenerate this issue in Github: /usr/local/src/opendatapolicing/roles/computate_org_github/defaults/main.yml
* Visit the OpenShift environment, click on your user name in the top right corner, and select "Copy Login Command" here: https://console.rh-us-east-1.openshift.com
* Paste that login command into a terminal. 
* Follow these steps to add the login IDs to the project: 

```bash
oc project opendatapolicing
oc policy add-role-to-user view christophertate
```

You can visit this site for more information: https://www.openshift.com/blog/add-collaborators-openshift-online-pro-account

**Comment by davidtluong** [comment]
@carbonin has done this on the shared cluster.
