### ISSUE TITLE
Create the SiteUser Java class

### ISSUE THREAD

**Issue by computate** [opendatapolicing/opendatapolicing#51]
# Mission Create the SiteUser Java class

![Mission:Impossible Open Data Policing](https://computate.neocities.org/gif/mission-impossible-opendatapolicing.gif "Mission:Impossible Open Data Policing")

Your mission, should you choose to accept it, is Create the SiteUser Java class. 

The [Southern Coalition for Social Justice](https://southerncoalition.org/) needs you to solve one of the world's most challenging problems: 

## The day of the operation is Martin Luther King Day, January 18th, 2021

You will have 24 hours to complete your mission. 

This platform allows users—including those in police management—to easily compare enforcement patterns among individual officers and agencies, 
evaluate the frequency and efficiency of searches, and monitor for racially disparate enforcement practices.

## In the words of Martin Luther King Jr.: 

- Now is the time to make real the promises of democracy. 
- Now is the time to lift our nation from the quicksands of racial injustice to the solid rock of brotherhood. 
- It would be fatal for the nation to overlook the urgency of the moment. 

# You will be joining a team of the boldest

of all Red Hatters for this mission, who will be at your service
developing the code and automating the deployment to OpenShift. 

- Let freedom ring from the mighty mountains of New York.
- Let freedom ring from the heightening Alleghenies of Pennsylvania. 
- Let freedom ring from the snow-capped Rockies of Colorado.
- Let freedom ring from the curvaceous slopes of California.
- From every mountainside, let freedom ring.

- Should you, or any of your force be taken or compromised that day, you must report back as many changes as you have made, and any knowledge of your actions, by pull request or comments on the issue on the board. 

## How to get started: 

Follow the instructions here to setup the project: https://github.com/opendatapolicing/opendatapolicing

## The details of your mission: 

- **The Java package name will be:** com.opendatapolicing.enus.user
- **The Java class name will be:** SiteUser
- **The Java class will extend:** SiteUserGen\<Cluster\>

```java
package com.opendatapolicing.enus.user;

import java.util.List;
import com.opendatapolicing.enus.cluster.Cluster;
import com.opendatapolicing.enus.wrap.Wrap;

/**
 * Model: true
 * Stored: true
 * Indexed: true
 * Saved: true

 * ApiUri.enUS: /api/user
 * ApiTag.enUS: User

 * ApiMethod: Search

 * ApiMethod: PATCH

 * ApiMethod: POST

 * ApiMethod: SearchPage.enUS
 * ApiUriSearchPage.enUS: /user
 * PageSearchPage.enUS: SiteUserPage
 * PageSuperSearchPage.enUS: SiteUserPage

 * AName.enUS: a site user
 * Color: 
 * IconGroup: regular
 * IconName: user-cog
 * NameVar: siteUser
 **/

public class SiteUser extends SiteUserGen<Cluster> {
}
```

## Create the userKeys entity

```java
protected void _userKeys(List<Long> l) {
		l.add(pk);
	}
```

## Create the userId entity

```java
	protected void _userId(Wrap<String> c) {
	}
```

## Create the userKey entity

```java
	protected void _userKey(Wrap<Long> c) {
	}
```

## Create the userName entity

```java
	protected void _userName(Wrap<String> c) {
	}
```

## Create the userEmail entity

```java
	protected void _userEmail(Wrap<String> c) {
	}
```

## Create the userFirstName entity

```java
	protected void _userFirstName(Wrap<String> c) {
	}
```

## Create the userLastName entity

```java
	protected void _userLastName(Wrap<String> c) {
	}
```

## Create the userFullName entity

```java
	protected void _userFullName(Wrap<String> c) {
	}
```

## Create the userSite entity

```java
	protected void _userSite(Wrap<String> c) {
	}
```

## Create the customerProfileId entity

```java
	protected void _customerProfileId(Wrap<String> c) {
	}
```

## Create the userReceiveEmails entity

```java
	protected void _userReceiveEmails(Wrap<Boolean> c) {
		c.o(false);
	}
```

## Create the seeArchived entity

```java
	protected void _seeArchived(Wrap<Boolean> c) {
		c.o(false);
	}
```

## Create the seeDeleted entity

```java
	protected void _seeDeleted(Wrap<Boolean> c) {
		c.o(false);
	}
```

## None

```java
	_objectTitle(Wrap<String> c) {
		c.o(userFullName + " " + userEmail + " " + userName);
	}
```

![This message will not self-destruct. ](https://computate.neocities.org/png/mission-impossible-message.png "This message will not self-destruct. ")

# This message will not self destruct, because this project is open source.

**Comment by kenfinnigan** [comment]
This is now closed
